version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: bus_scheduler_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bus_scheduler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend i Frontend zostanÄ… dodane w kolejnych krokach

volumes:
  postgres_data:
